### ISSUE TITLE
Lambda code doesn't respond appropriately when a key is missing

### ISSUE THREAD

**Issue by DylanSp** [jheller/alb-rule#1]
I ran into an error when trying to use this; I forgot to add a Priority key in the CloudFormation template, and the custom resource got stuck in creation. CloudWatch logs showed the following:
```
'Priority': KeyError
Traceback (most recent call last):
File "/var/task/alb_rule.py", line 19, in lambda_handler
Priority = int(event['ResourceProperties']['Priority'])
KeyError: 'Priority'
```
Because line 19 isn't in the try block, there wasn't an exception handler to send a `'FAILED'` response. In order to get CloudFormation to clean up the resource, I had to edit the Lambda function to send `'FAILED'`, which allowed CloudFormation to see that creation had failed. Is there an easy way to change the code to handle missing keys, so CloudFormation can detect errors?

**Comment by jheller** [comment]
Thanks for the feedback. I've moved everything into the try block. All exceptions, including missing or misspelt parameters, should now be handled.

Can you test that it resolved the issue you had.

**Comment by DylanSp** [comment]
Looks like that mostly did the trick; I created a test template with the priority missing, and CloudFormation detected the error quickly and attempted to cancel the resource creation. The only problem I still see is that the Delete request CloudFormation sends also fails due to the key error. This shouldn't be too much of a problem, as the resource didn't get created in the first place, but it's mildly annoying. Not sure what you can do about it, though.

Thanks for writing this library, by the way. It's very helpful.

**Comment by jheller** [comment]
Delete requests will not come from Cloudformation unless there has already been a successful create. If you have an alternative way of handling delete's feel free to raise a pull request.

Thanks again for your feedback.
